### ISSUE TITLE
Frontend discussion

### ISSUE THREAD

**Issue by wildmolasses** [ScopeLift/zeneth#4]

**Comment by mds1** [comment]
I think we want two forms to start:
1. An ERC20 form, for end-to-end testing on Goerli
2. An L2 entry form, for use on mainnet / demo purposes

So maybe something like this:
1. The app is a single page
2. On that page, you can choose between various "actions". Kind of like how the Umbra site lets you choose "Send" or "Receive", this would let you choose "Send tokens" or "Deposit into L2"
3. Clicking either shows the appropriate form
4. ERC20 form:
    1. Dropdown to select a token (should only show a few approved ones, like ETH, DAI, USDC, USDT
    2. Enter an amount
    3. Enter a recipient address
    4. Optional "miner fee" field, which defaults to some TBD value but can be overriden by the user
5. L2 form
    1. Dropdown to choose an L2 (we'll need to add them one by one, maybe start with just zkSync for now since we're most familiar with it)
    2. Dropdown to select a token (should only show a few approved ones, like ETH, DAI, USDC, USDT
    3. Enter an amount
    4. Optional "miner fee" field, which defaults to some TBD value but can be overriden by the user

So the token selection and miner fee fields can be shared by both forms. The miner fee is ultimately specified in ETH, but for the sake of showing fees to the user we may want to show it in token units, or both units?

Upon submitting the form, the user will need to sign 3 transactions
1. Sign transaction to send token / enter L2
2. Sign transaction to approve our `SwapBriber` to spend their tokens
3. Sign transaction to call `SwapBriber.swapAndBribe` on our contract

Pass those 3 signed transactions to zeneth-js to send them
