### ISSUE TITLE
zeneth-js Test Failure

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/zeneth#53]
Getting the following simulation failure on `main` when running `yarn test` in zeneth-js:

<img width="648" alt="Screen Shot 2021-06-30 at 10 44 05 PM" src="https://user-images.githubusercontent.com/1479802/124057143-ef010080-d9f4-11eb-90e4-cdaa1455e9a7.png">

**Comment by mds1** [comment]
This is not a test failure 🙂

You'll see that zeneth-js [logs](https://github.com/ScopeLift/zeneth/blob/1fa9918c8dae517d3148cc586cdd5af77a29c774/zeneth-js/src/relayer.ts#L154-L158) info about simulation failures, and as shown in the screenshot below, that log is printed immediately before a successful test for `does not send bundles with transactions that revert`. In other words, we have a test for simulation failures, so a simulation failure is expected to be logged to the console

![image](https://user-images.githubusercontent.com/17163988/124112153-da396280-da1e-11eb-840d-ffd4478f785f.png)
